server:
  port: 8081
  
spring:
   datasource:
      password: 12345
      username: root
      url: jbdc:mysql://localhost:3306/fornecedor
   jpa:
       hibernate:
          ddl-auto: create
      